healthCheckTimeout: 5000
logRequests: true

models:
  qwen2.5-14b:
    proxy: http://127.0.0.1:9999
    cmd: >
      /app/llama-server 
      --model /models/Qwen2.5-Coder-14B-Instruct-Q4_K_L.gguf
      --ctx-size 2048
      --temp 0.05
      --port 9999
      --gpu-layers 999
      --cache-type-k q8_0
      --cache-type-v q8_0
      --flash-attn
      --no-webui
    ttl: 60

  qwen2.5-14b-draft:
    proxy: http://127.0.0.1:9999
    cmd: >
      /app/llama-server 
      --model /models/Qwen2.5-Coder-14B-Instruct-Q4_K_L.gguf
      --ctx-size 2048
      --gpu-layers 999
      --model-draft /models/Qwen2.5-Coder-0.5B-Instruct-Q4_K_L.gguf
      --ctx-size-draft 2048
      --gpu-layers-draft 999
      --draft-max 16
      --draft-min 4
      --draft-p-min 0.4
      --temp 0.05
      --port 9999
      --cache-type-k q8_0
      --cache-type-v q8_0
      --flash-attn
      --no-webui
    ttl: 60
  
  gemma3-12b:
    proxy: http://127.0.0.1:9999
    cmd: >
      /app/llama-server 
      --model /models/gemma-3-12b-it-q4_0_s.gguf
      --ctx-size 2048
      --temp 0.05
      --port 9999
      --gpu-layers 999
      --cache-type-k q8_0
      --cache-type-v q8_0
      --flash-attn
      --no-webui
    ttl: 60