network:
  host: 0.0.0.0
  port: 5000
  disable_auth: true
  disable_fetch_requests: false
  send_tracebacks: false
  api_servers: ["OAI"]

logging:
  log_prompt: false
  log_generation_params: false
  log_requests: false

model:
  model_dir: /app/models
  cache_mode: Q8
  inline_model_loading: true

draft_model:
  draft_model_dir: /app/models
  draft_rope_scale: 1.0
  draft_cache_mode: Q8

embeddings:
  embedding_model_dir: /app/models
  embeddings_device: cpu

developer:
  disable_request_streaming: false
  cuda_malloc_backend: false
  realtime_process_priority: false
